notice/config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admins
  devise_for :members,  controllers: {
    registrations: "members/registrations"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: 'homes#top'
  resources :posts do
   resources :comments
  end
  get 'familycodes/searchmember' => 'familycodes#searchmember', as: :searchmember

  #退会処理
  get 'members/leave' => 'members#leave'
  get 'users/leave' => 'users#leave'
  patch 'members/withdraw' => 'members#withdraw', as: :members_withdraw
  patch 'users/withdraw' => 'users#withdraw', as: :users_withdraw

  get 'familycodes/searchuser' => 'familycodes#searchuser', as: :searchuser
  resources :familycodes, only: [:new, :create, :destroy]
  get 'familycodes/result' => 'familycodes#result'
  resources :members
  resources :questions
  resources :users
  get 'users/show' => 'users#show'
  resources :admins

  #お問い合わせ
  resources :inquiries, only: [:new, :create], param: :name
  get 'inquiries/:name/:id' => 'inquiries#show'
  # get 'inquiries/:name/:id/edit' => 'inquiries#edit'
  # patch 'inquiries/:name/:id' => 'inquiries#update'
  # put 'inquiries/:name/:id' => 'inquiries#update'
  get 'admin/sign_in' => 'admin#sign_in'
  namespace :admin do
    resources :members do
      collection do
        get 'search'
      end
    end

    resources :inquiries, only:[:index, :edit, :update] do
      collection do
        get 'search'
      end
    end

    resources :users do
     collection do
      get 'search'
     end
    end



    resources :posts, controllers: {
    registrations: "posts"
  }

    resources :familycodes do
      collection do
        get 'search'
      end
    end
  end
end

notice/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

notice/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

notice/app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :member
  belongs_to :post

  validates :comment, presence: true

end

notice/app/models/familycode.rb
class Familycode < ApplicationRecord

  has_many :users, dependent: :destroy
  has_many :members, dependent: :destroy
  validates :famcode, uniqueness: true, length: {minimum: 8}

end

notice/app/models/inquiry.rb
class Inquiry < ApplicationRecord
  #件名
  enum title: {本ウェブサイトの使い方:0, 本ウェブサイトの問題点:1, 本ウェブサイトへの質問:2, 管理者への質問:3,退会済みのお客様:4, その他:5}

  validates :name, presence: true
  validates :email, presence: true
  validates :inquiry, presence:true

# def to_param
#   return self.name
# end
end

notice/app/models/member.rb
class Member < ApplicationRecord
  include Hashid::Rails
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :family_codes
  # has_many :member_familycodes
  belongs_to :familycode
  has_many :comments, dependent: :destroy
  has_many :questions, dependent: :destroy

  attachment :profile_image



  #住所選択用
  enum address_area:{
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
   }

  #性別選択用
   enum gender: {男性:1, 女性:2, 回答無し: 3}

  #退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :name, length: { minimum: 2, maximum: 20 }
  validates :name_kana, length: { minimum: 2, maximum: 20 }
  validates :telephone_number, length: { minimum: 10, maximum: 11 }
  validates :familycode_id, presence: true
  validates :nickname, length: { minimum: 1, maximum: 10 }
  validates :email, uniqueness: true

end

notice/app/models/member_familycode.rb
class MemberFamilycode < ApplicationRecord
  # belongs_to :familycode, optional: true
  # belongs_to :member, optional: true
end

notice/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  # attachment :profile_image
  has_many :comments, dependent: :destroy

  validates :post, presence: true
end

notice/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :member
  belongs_to :user

  validates :user_id, presence: true
  validates :body, presence: true
  validates :choices1, length: { minimum: 1, maximum: 10 }
  validates :choices2, length: { minimum: 1, maximum: 10 }
end

notice/app/models/see.rb
class See < ApplicationRecord
end

notice/app/models/user.rb
class User < ApplicationRecord
  include Hashid::Rails
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :familycode
  has_many :posts, dependent: :destroy
  has_many :questions, dependent: :destroy

  attachment :profile_image

  #住所用
    enum address_area:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }

#性別
  enum gender: {男性:1, 女性:2, 回答無し: 3}

  #退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :name, length: { in: 2..20 }
  validates :name_kana, length: { minimum: 2, maximum: 20 }
  validates :telephone_number, length: { minimum: 10, maximum: 11 }
  validates :familycode_id, presence: true
  validates :nickname, length: { minimum: 1, maximum: 10 }
  validates :email, uniqueness: true
end

notice/app/helpers/application_helper.rb
module ApplicationHelper
  def sorttable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

  def date_select_ja(src_html)
    dst_html = src_html.gsub(/>\d{4}</) do |m|
      year = m.match(/>(\d{4})</)[1].to_i
      year_ja = case year
        when 0..1911
          "明治#{year - 1867}"
        when 1912
          "明治45/大正元年"
        when 1913..1925
          "大正#{year - 1911}"
        when 1926
          "大正15/昭和元年"
        when 1927..1988
          "昭和#{year - 1925}"
        when 1989
          "昭和64/平成元年"
        when 1990..2018
          "平成#{year - 1988}"
        when 2019
          "平成31年/令和元年"
        else
          "令和#{year-2018}"
      end
      ">#{year_ja} (#{year})<"
    end
    dst_html.html_safe
  end
end

notice/app/helpers/comments_helper.rb
module CommentsHelper
end

notice/app/helpers/homes_helper.rb
module HomesHelper
end

notice/app/helpers/inquiries_helper.rb
module InquiriesHelper
end

notice/app/helpers/inquiry_helper.rb
module InquiryHelper
end

notice/app/helpers/members_helper.rb
module MembersHelper
end

notice/app/helpers/posts_helper.rb
module PostsHelper
end

notice/app/helpers/questions_helper.rb
module QuestionsHelper
end

notice/app/helpers/users_helper.rb
module UsersHelper
end

notice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="robots" content="nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
    <meta name="description" content="このサイトは離れている家族の距離を無くす無料SNSサイトです。" />
    <meta name="keywords" content="おじいちゃん, おばあちゃん, 家族, 温かい, Warm, 暖かい家族, familykamatyo, ふぁみりーかまちょ, 小田純平" />
    <meta name="author" content="小田純平" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body class="d-flex flex-column vh-100 background_image">
    <header class="shadow-sm">
      <nav class="navbar navbar-light justfy-content-between nav-back">
        <div class="container-fluid">
          <a class="navbar-brand p-2" href="/"><div class="webtitle"></div></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if member_signed_in? %>
                <li class="nav-item"><%= link_to 'プロフィール', member_path(current_member), class: "nav-text" %></li>
                <li class="nav-item"><%= link_to '投稿一覧', posts_path, class: "nav-text" %></li>
                <li class="nav-item"><%= link_to '質問投稿', new_question_path, class: "nav-text" %></li>
                <li class="nav-item"><%= link_to '質問一覧', questions_path, class: "nav-text" %></li>
                <li class="nav-item"><%= link_to 'お問い合わせ', new_inquiry_path, class:"nav-text" %></li>
                <li class="nav-item"><%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "nav-text" %></li>
              <% elsif user_signed_in? %>
                <li class="nav-item"><%= link_to 'プロフィール', user_path(current_user), class: "nav-text" %></li>
                <li class="nav-item"><%= link_to '投稿画面', new_post_path, class: "nav-text" %></li>
                <li class="nav-item"><%= link_to 'お問い合わせ', new_inquiry_path, class:"nav-text" %></li>
                <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-text" %></li>
              <% elsif admin_signed_in? %>
                <li class="nav-item"><%= link_to '投稿会員一覧', admin_users_path , class: "btn btn-warning" %></li>
                <li class="nav-item"><%= link_to '家族会員一覧', admin_members_path, class: "btn btn-warning" %></li>
                <li class="nav-item"><%= link_to '投稿一覧', admin_posts_path, class: "btn btn-warning" %></li>
                <li class="nav-item"><%= link_to '家族コード一覧', admin_familycodes_path, class: "btn btn-warning" %></li>
                <li class="nav-item"><%= link_to "お問い合わせ画面", admin_inquiries_path, class:"btn btn-warning" %></li>
                <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-warning" %></li>
              <% else %>
                <li class="nav-item"><%= link_to '家族コード作成', new_familycode_path, class: "nav-text" %></li>
                <li class="nav-item"><%= link_to '家族会員登録', new_member_registration_path, class: "nav-text" %></li>
                <li class="nav-item"><%= link_to '家族会員ログイン', member_session_path, class: "nav-text" %></li>
                <li class="nav-item"><%= link_to '投稿会員登録', new_user_registration_path, class: "nav-text" %></li>
                <li class="nav-item"><%= link_to '投稿会員ログイン', user_session_path, class: "nav-text" %></li>
                <li class="nav-item"><%= link_to 'お問い合わせ', new_inquiry_path, class:"nav-text" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <% if member_signed_in? %>
        <div class= "welcome">
          <span class="name">ようこそ!!<%= current_member.name %>様</span>
        </div>
      <% elsif user_signed_in? %>
        <div class= "welcome">
          <span class="name">ようこそ!!<%= current_user.name %>様</span>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <footer class="text-black pt-5 pb-4">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <p><i class="fab fa-ussunnah"></i>安心の暮らし作りをお手伝いする<strong>SNS</strong></p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>