notice/config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admins
  devise_for :members,  controllers: {
    registrations: "members/registrations"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: 'homes#top'
  resources :posts do
   resources :comments
  end
  get 'familycodes/searchmember' => 'familycodes#searchmember', as: :searchmember

  #退会処理
  get 'members/leave' => 'members#leave'
  get 'users/leave' => 'users#leave'
  patch 'members/withdraw' => 'members#withdraw', as: :members_withdraw
  patch 'users/withdraw' => 'users#withdraw', as: :users_withdraw

  get 'familycodes/searchuser' => 'familycodes#searchuser', as: :searchuser
  resources :familycodes, only: [:new, :create, :destroy]
  get 'familycodes/result' => 'familycodes#result'
  resources :members
  resources :questions
  resources :users
  get 'users/show' => 'users#show'
  resources :admins

  #お問い合わせ
  resources :inquiries, only: [:new, :create], param: :name
  get 'inquiries/:name/:id' => 'inquiries#show'
  # get 'inquiries/:name/:id/edit' => 'inquiries#edit'
  # patch 'inquiries/:name/:id' => 'inquiries#update'
  # put 'inquiries/:name/:id' => 'inquiries#update'
  get 'admin/sign_in' => 'admin#sign_in'
  namespace :admin do
    resources :members do
      collection do
        get 'search'
      end
    end

    resources :inquiries, only:[:index, :edit, :update] do
      collection do
        get 'search'
      end
    end

    resources :users do
     collection do
      get 'search'
     end
    end



    resources :posts, controllers: {
    registrations: "posts"
  }

    resources :familycodes do
      collection do
        get 'search'
      end
    end
  end
end

notice/app/models/member.rb
class Member < ApplicationRecord
  include Hashid::Rails
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :family_codes
  # has_many :member_familycodes
  belongs_to :familycode
  has_many :comments, dependent: :destroy
  has_many :questions, dependent: :destroy

  attachment :profile_image



  #住所選択用
  enum address_area:{
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
   }

  #性別選択用
   enum gender: {男性:1, 女性:2, 回答無し: 3}

  #退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :name, length: { minimum: 2, maximum: 20 }
  validates :name_kana, length: { minimum: 2, maximum: 20 }
  validates :telephone_number, length: { minimum: 10, maximum: 11 }
  validates :familycode_id, presence: true
  validates :nickname, length: { minimum: 1, maximum: 10 }
  validates :email, uniqueness: true

end

notice/app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
 before_action :authenticate_admin!
 before_action :set_q, only: [:index, :search]
 helper_method :sort_column, :sort_direction
  def index
    @members = Member.all.order(sort_column+ ' ' + sort_direction).page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
    @familymembers = Member.where(familycode_id: @member.familycode_id)
    @familyusers = User.where(familycode_id: @member.familycode_id)
    @member_score = @member.comments.all.sum(:score)
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to admin_members_path
  end

  def search
    @results = @q.result.order(sort_column+ ' ' + sort_direction).page(params[:page]).per(10)
  end


  private

    def sort_direction
      %w[asc desc].include?(params[:direction])? params[:direction] : "asc"
    end

    def sort_column
      Member.column_names.include?(params[:sort])? params[:sort] : "name"
    end

    def set_q
      @q = Member.ransack(params[:q])
    end
end

notice/app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

notice/app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

notice/app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

notice/app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
    #def new


      #super
   # end

  # def search
  #
  #   @familycode = Familycode.where(family_code: "#{params[:cd]}")
  #   render :new
  # end

  # POST /resource
  def create
      super
      if @member.save
        WelcomeMemberMailer.send_when_signup(params[:member][:email],params[:member][:name]).deliver
        # tags = Vision.get_image_data(@member.profile_image)
        # tags.each do |tag|
        #   member.tags.create(name: tag)
        # end
      end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

notice/app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_member, only: [:create]


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_member
    @member = Member.find_by(email: params[:member][:email].downcase)
    if (@member.valid_password?(params[:member][:password]) && (@member.active_for_authentication? == false))
      render new_member_session_path
    end
  end
end

notice/app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

notice/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_member!

  def show
    @member = Member.find(current_member.id)
    @familymembers = Member.where(familycode_id: current_member.familycode_id)
    @familyusers = User.where(familycode_id: current_member.familycode_id)
  end

  def edit
    @member = Member.find(current_member.id)
  end

  def update
    @member = Member.find(current_member.id)
    if @member.update(member_params)
      redirect_to member_path(current_member.id)
    else
      render :edit
    end
  end

  def leave
    @member = Member.find(current_member.id)
  end

  def withdraw
    @member = Member.find(current_member.id)
    @member.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def member_params
    params.require(:member).permit(:name, :name_kana, :telephone_number, :birth_date, :address, :email, :is_deleted, :profile_image, :familycode_id, :gender, :nickname)
  end



end

notice/app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

notice/app/helpers/members/comments_helper.rb
module Members::CommentsHelper
end

notice/app/helpers/members/posts_helper.rb
module Members::PostsHelper
end

notice/app/helpers/members_helper.rb
module MembersHelper
end

notice/app/views/members/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-10 offset-sm-1 col-md-10 offset-md-1">
      <h1>家族会員プロフィール情報編集</h1>
    </div>
    <div class= "col-xs-12 col-sm-10 offset-sm-1 col-md-6 offset-md-3">
      <% if @member.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <strong>入力内容にエラーがあります</strong>
          <ul>
            <% @member.errors.each do |attr, msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@member, url:member_path(@member), local:true do |f| %>
      <%= render "members/shared/error_messages", resource: @member %>
      <table class="table tablef">
        <tr>
          <th>
            <h3><%= f.label :profile_image, "顔写真" %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <h4><%= f.attachment_field :profile_image, size: "200x200" %></h4>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :name, "氏名" %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <%= f.text_field :name, autofocus: true, placeholder:"山田太郎", class:"form-size" %>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :name_kana, "カナ氏名" %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <%= f.text_field :name_kana, placeholder: "ヤマダタロウ", class:"form-size" %>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :nickname, "ニックネーム" %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <%= f.text_field:nickname, placeholder: "ヤーマダ", class:"form-size" %>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :gender, "性別" %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <h3>
              <%= f.radio_button :gender, :男性 %>
              <%= f.label :"男性" %>
              <%= f.radio_button :gender, :女性 %>
              <%= f.label :"女性" %>
              <%= f.radio_button :gender, :回答無し %>
              <%= f.label :"回答無し" %>
            </h3>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :telephone_number, "電話番号" %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <%= f.number_field :telephone_number, placeholder: "ハイフン無しで入力下さい", class:"form-size" %>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :birth_date, "生年月日" %></h3>
          </th>
        </tr>
        <tr>
          <td>
             <h3><%= date_select_ja(f.date_select(:birth_date, start_year:2018, end_year:1900)) %></h3>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :address, "都道府県" %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <%= f.select :address, User.address_areas.keys, {} %>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :email, "メールアドレス" %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <%= f.email_field :email, autocomplete: "email", class:"form-size" %>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :password, "パスワード" %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, placeholder: "変更時のみ入力下さい", autocomplete: "new-password", class:"form-size" %>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :password_confirmation, "パスワード確認"%></h3>
          </th>
        </tr>
        <tr>
          <td>
            <%= f.password_field :password_confirmation, placeholder: "変更時のみ入力下さい", autocomplete: "new-password", class:"form-size" %>
          </td>
        </tr>
        <tr>
          <th>
            <h3><%= f.label :famcode, "家族コード" %></h3>
          </th>
        </tr>
        <tr>
          <td class="text-danger">
            <h3><strong>編集不可</strong></h3>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.submit "更新する", class:"btn btn-outline-success", size:20 %>
            <%= link_to "退会する", members_leave_path %><br>
          </td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

notice/app/views/members/leave.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2">
      <h1>本当に退会しますか？</h1>
      <p>退会すると、会員登録情報やこれまでの投稿が閲覧できなくなります。</p>
      <p>退会する場合は、「退会する」をクリックしてください</p>
      <% if member_signed_in? && @member.id == current_member.id %>
        <%= link_to "退会しない",  edit_member_path(@member) , class:"btn btn-primary" %>
        <%= link_to "退会する",members_withdraw_path(current_member), method: :patch, class:"btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

notice/app/views/members/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-8 offset-sm-2 col-md-10 offset-md-1">
      <h1>家族会員プロフィール詳細</h1>
    </div>
    <div class="col-xs-12 col-sm-8 offset-sm-2 col-md-4 offset-md-4">
      <table class="table tablef text-center">
        <tr>
          <th>
            <h3>顔写真</h3>
          </th>
        </tr>
        <tr>
          <td class:"text-center">
            <% if @member.gender == "男性" %>
              <%= attachment_image_tag @member, :profile_image, size:"150x150", format: 'jpeg', fallback:"men.png" %>
            <% elsif @member.gender == "女性" %>
              <%= attachment_image_tag @member, :profile_image, size:"150x150", format: 'jpeg', fallback:"women.png" %>
            <% else %>
              <%= attachment_image_tag @member, :profile_image, size:"150x150", format: 'jpeg', fallback:"no-image.jpg" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>
            <h3>氏名</h3>
          </th>
        </tr>
        <tr>
          <td>
            <h2><%= @member.name %></h2>
          </td>
        </tr>
        <tr>
          <th>
            <h3>氏名カナ</h3>
          </th>
        </tr>
        <tr>
          <td>
            <h2><%= @member.name_kana %></h2>
          </td>
        </tr>
        <tr>
          <th>
            <h3>ニックネーム</h3>
          </th>
        </tr>
        <tr>
          <td>
            <h2><%= @member.nickname %></h2>
          </td>
        </tr>
        <tr>
          <th>
            <h3>性別</h3>
          </th>
        </tr>
        <tr>
          <td>
            <h2><%= @member.gender %></h2>
          </td>
        </tr>
        <tr>
          <th>
            <h3>電話番号</h3>
          </th>
        </tr>
        <tr>
          <td>
            <h2><%= link_to @member.telephone_number, "tel:" + @member.telephone_number %></h2>
          </td>
        </tr>
        <tr>
          <th>
            <h3>生年月日</h3>
          </th>
        </tr>
        <tr>
          <td>
            <h2><%= @member.birth_date %></h2>
          </td>
        </tr>
        <tr>
          <th>
            <h3>都道府県</h3>
          </th>
        </tr>
        <tr>
          <td>
            <h2><%= @member.address %></h2>
          </td>
        </tr>
        <tr>
          <th>
            <h3>メールアドレス</h3>
          </th>
        </tr>
        <tr>
          <td>
            <h2><%= @member.email %></h2>
          </td>
        </tr>
        <tr>
          <th>
            <h3>家族コード</h3>
          </th>
        </tr>
        <tr>
          <td>
            <h2><%= @member.familycode.famcode %></h2>
          </td>
        </tr>
        <tr>
          <th>
            <h3>家族の投稿者一覧</h3>
          </th>
        </tr>
        <tr>
          <td>
            <% @familyusers.each do |familyuser| %>
              ・<%= familyuser.name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>
            <h3>家族メンバー一覧</h3>
          </th>
        </tr>
        <tr>
          <td>
            <% @familymembers.each do |familymember| %>
              ・<%= familymember.name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>
            <h3 class="text-left"><%= link_to "プロフィール情報を編集する", edit_member_path(@member) %></h3>
          </th>
        </tr>
        <tr>
          <td>
            <h3 class="text-left"><%= link_to "投稿一覧画面へ", posts_path %></h3>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>