notice/config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admins
  devise_for :members,  controllers: {
    registrations: "members/registrations"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: 'homes#top'
  resources :posts do
   resources :comments
  end
  get 'familycodes/searchmember' => 'familycodes#searchmember', as: :searchmember

  #退会処理
  get 'members/leave' => 'members#leave'
  get 'users/leave' => 'users#leave'
  patch 'members/withdraw' => 'members#withdraw', as: :members_withdraw
  patch 'users/withdraw' => 'users#withdraw', as: :users_withdraw

  get 'familycodes/searchuser' => 'familycodes#searchuser', as: :searchuser
  resources :familycodes, only: [:new, :create, :destroy]
  get 'familycodes/result' => 'familycodes#result'
  resources :members
  resources :questions
  resources :users
  get 'users/show' => 'users#show'
  resources :admins

  #お問い合わせ
  resources :inquiries, only: [:new, :create], param: :name
  get 'inquiries/:name/:id' => 'inquiries#show'
  # get 'inquiries/:name/:id/edit' => 'inquiries#edit'
  # patch 'inquiries/:name/:id' => 'inquiries#update'
  # put 'inquiries/:name/:id' => 'inquiries#update'
  get 'admin/sign_in' => 'admin#sign_in'
  namespace :admin do
    resources :members do
      collection do
        get 'search'
      end
    end

    resources :inquiries, only:[:index, :edit, :update] do
      collection do
        get 'search'
      end
    end

    resources :users do
     collection do
      get 'search'
     end
    end



    resources :posts, controllers: {
    registrations: "posts"
  }

    resources :familycodes do
      collection do
        get 'search'
      end
    end
  end
end

notice/app/models/user.rb
class User < ApplicationRecord
  include Hashid::Rails
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :familycode
  has_many :posts, dependent: :destroy
  has_many :questions, dependent: :destroy

  attachment :profile_image

  #住所用
    enum address_area:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }

#性別
  enum gender: {男性:1, 女性:2, 回答無し: 3}

  #退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :name, length: { in: 2..20 }
  validates :name_kana, length: { minimum: 2, maximum: 20 }
  validates :telephone_number, length: { minimum: 10, maximum: 11 }
  validates :familycode_id, presence: true
  validates :nickname, length: { minimum: 1, maximum: 10 }
  validates :email, uniqueness: true
end

notice/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_action :authenticate_admin!
before_action :set_q, only: [:index, :search]
helper_method :sort_column, :sort_direction

  def index
    @users = User.all.order(sort_column+ ' ' + sort_direction).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @familymembers = Member.where(familycode_id: @user.familycode_id)
    @familyusers = User.where(familycode_id: @user.familycode_id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def search
    @results = @q.result.order(sort_column+ ' ' + sort_direction).page(params[:page]).per(10)
  end

  private

    def sort_direction
      %w[asc desc].include?(params[:direction])? params[:direction] : "asc"
    end

    def sort_column
      User.column_names.include?(params[:sort])? params[:sort] : "name"
    end

    def set_q
      @q = User.ransack(params[:q])
    end
end

notice/app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
end

notice/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

notice/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

notice/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

notice/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
    #def new
      #@user = User.new
      # if params[:word].present?
      #   @word = params[:word]
      #   @familycodes = search(@word , Familycode)
      # end
      #super
   # end

    # def search
    #   items = item.all
    #   if word.present?
    #     items = items.where("")

  # POST /resource
  def create
    # familycode = Familycode.find(params[:member][:familycode_id])
    # @familycode = familycode.famcode
    # @familycode_id = familycode.id
     super
     if @user.save
      WelcomeMailer.send_when_signup(params[:user][:email],params[:user][:name]).deliver
     end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

notice/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def reject_member
    @user = User.find_by(email: params[:user][:email].downcase)
    if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
      render new_user_session_path
    end
  end
end

notice/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

notice/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def leave
    @user = User.find(current_user.id)
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :name_kana, :telephone_number, :birth_date, :address, :fire, :email, :is_deleted, :profile_image, :familycode_id, :gender, :nickname)
  end
end

notice/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

notice/app/helpers/users/comments_helper.rb
module Users::CommentsHelper
end

notice/app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

notice/app/helpers/users_helper.rb
module UsersHelper
end

notice/app/views/admin/users/index.html.erb
<div class="container-fuluid">
  <div class="row">
    <div class="col-md-8"></div>
    <div class="col-md-4">
      <%= search_form_for @q, url: search_admin_users_path do |f| %>
        <%= f.label :email, 'メールアドレス' %>
        <%= f.search_field :email_cont %>
        <% f.submit '検索' %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 offset-1">
      <h1>投稿会員一覧(現在<%= @users.count %>人の登録者)</h1>
      <table class="table text-center">
        <thead class="text-center">
          <tr>
            <th class="text-center"><%= sorttable "id", "ID" %></th>
            <th class="text-center"><%= sorttable "name_kana", "氏名" %></th>
            <th class="text-center"><%= sorttable "gender", "性別" %></th>
            <th class="text-center"><%= sorttable "address","都道府県" %></th>
            <th class="text-center"><%= sorttable "telephone_number", "電話番号" %></th>
            <th class="text-center"><%= sorttable "email", "メールアドレス" %></th>
            <th class="text-center"><%= sorttable "is_deleted", "ステータス" %></th>
            <th class="text-center"><%= sorttable "created_at", "登録日時" %></th>
          </tr>
        </tread>
        <% @users.each do |user| %>
        <tbody class="text-center">
        <tr>
          <th class="text-center">
            <%= user.id %>
          </th>
          <td class="text-center">
            <%= link_to admin_user_path(user) do %>
              <%= user.name %>
            <% end %>
          </td>
          <td class="text-center">
            <%= user.gender %>
          </td>
          <td class="text-center">
            <%= user.address %>
          </td>
          <td class="text-center">
            <%= user.telephone_number %>
          </td>
          <td class="text-center">
            <%= user.email %>
          </td>
          <td class="text-center">
            <% if user.is_deleted? %>
              <p class="text-danger">退会</p>
            <% else %>
              <p class="text-success">有効</p>
            <% end %>
          </td>
          <td class="text-center">
            <%= user.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          </td>
        </tbody>
        <% end %>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

notice/app/views/admin/users/search.html.erb
<div class="container-fuluid">
  <div class="row">
    <div class="col-md-8"></div>
    <div class="col-md-4">
      <%= search_form_for @q, url: search_admin_users_path do |f| %>
        <%= f.label :email_cont, 'メールアドレス' %>
        <%= f.search_field :email_cont, placeholder:"メールアドレス" %>
        <% f.submit '検索' %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 offset-1">
      <h1>投稿会員検索結果</h1>
      <table class="table">
        <thead>
          <tr>
            <th class="text-center">ID</th>
            <th class="text-center">氏名</th>
            <th class="text-center">性別</th>
            <th class="text-center">都道府県</th>
            <th class="text-center">電話番号</th>
            <th class="text-center">メールアドレス</th>
            <th class="text-center"><%= sort_link(@q, :created_at, "登録日時") %></th>
          </tr>
        </thead>
        <% @results.each do |user| %>
        <tbody>
        <tr>
          <th class="text-center">
            <%= user.id %>
          </th>
          <td class= "text-center">
            <%= link_to admin_user_path(user) do %>
              <%= user.name %>
            <% end %>
          </td>
          <td class= "text-center">
            <%= user.gender %>
          </td>
          <td class= "text-center">
            <%= user.address %>
          </td>
          <td class= "text-center">
            <%= user.telephone_number %>
          </td>
          <td class= "text-center">
            <%= user.email %>
          </td>
          <td class= "text-center">
            <%= user.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          </td>
        </tbody>
        <% end %>
      </table>
      <%= paginate @results %>
    </div>
  </div>
</div>

notice/app/views/admin/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-10 offset-1">
      <p class="page-title">
       <h1>投稿会員詳細
         <% if @user.is_deleted? %>
           <span class="text-danger">(退会中)</span>
         <% else %>
           <span class="text-success">(有効)</span>
         <% end %>
       </h1>
      </p>
      <table class="table">
        <tr>
          <th>
            氏名(投稿数)
          </th>
          <td>
            <%= @user.name %>(<%= @user.posts.count %>)
          </td>
        </tr>
        <tr>
          <th>
            氏名カナ
          </th>
          <td>
            <%= @user.name_kana %>
          </td>
        </tr>
        <tr>
          <th>
            ニックネーム
          </th>
          <td>
            <%= @user.nickname %>
          </td>
        </tr>
          <th>
            性別
          </th>
          <td>
            <%= @user.gender %>
          </td>
        <tr>
          <th>
            電話番号
          </th>
          <td>
            <%= @user.telephone_number %>
          </td>
        </tr>
        <tr>
          <th>
            生年月日
          </th>
          <td>
            <%= @user.birth_date %>
          </td>
        </tr>
         <tr>
          <th>
            都道府県
          </th>
          <td>
            <%= @user.address %>
          </td>
        </tr>
        <tr>
          <th>
            メールアドレス
          </th>
          <td>
            <%= @user.email %>
          </td>
        </tr>
        <tr>
          <th>
            家族コード
          </th>
          <td>
            <%= link_to admin_familycode_path(@user.familycode_id) do %>
              <%= @user.familycode.famcode %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>
            家族の投稿者一覧
          </th>
          <td>
            <% @familyusers.each do |familyuser| %>
              <%= link_to admin_user_path(familyuser) do %>
                ・<%= familyuser.name %>
              <% end %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>
            <div>
              家族メンバー一覧
            </div>
          </th>
          <td>
            <% @familymembers.each do |familymember| %>
              <%= link_to admin_member_path(familymember) do %>
                ・<%= familymember.name %>
              <% end %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>
            <%= link_to "削除する", admin_user_path(@user),method: :delete, class:"btn btn-danger" %>
          </th>
        </tr>
      </table>
    </div>
  </div>
</div>
<!--%= line_chart @user.posts.group_by_day(:created_at).count %>-->